// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextAdminAuth.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NextAdminAuth.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251212205529_AddSoftDelete")]
    partial class AddSoftDelete
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NextAdminAuth.Api.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Tckn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Tckn")
                        .IsUnique();

                    b.ToTable("Customers", t =>
                        {
                            t.HasCheckConstraint("CK_Customer_Tckn_NoLeadingZero", "\"Tckn\" NOT LIKE '0%'");
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0539e77-8ab6-49f1-b8f3-c16fba604996"),
                            CreatedAt = new DateTime(2025, 12, 12, 20, 55, 29, 526, DateTimeKind.Utc).AddTicks(1400),
                            Icon = "LayoutDashboard",
                            IsActive = true,
                            IsDeleted = false,
                            Order = 1,
                            Path = "/dashboard",
                            Title = "Ana Sayfa"
                        },
                        new
                        {
                            Id = new Guid("827d783b-15dc-40cc-bb5b-5f6c90368b43"),
                            CreatedAt = new DateTime(2025, 12, 12, 20, 55, 29, 526, DateTimeKind.Utc).AddTicks(2490),
                            Icon = "Users",
                            IsActive = true,
                            IsDeleted = false,
                            Order = 2,
                            Path = "#",
                            Title = "Yönetim"
                        },
                        new
                        {
                            Id = new Guid("fdbbb6f4-eca1-4856-a00a-ae568c49538c"),
                            CreatedAt = new DateTime(2025, 12, 12, 20, 55, 29, 526, DateTimeKind.Utc).AddTicks(2490),
                            Icon = "Settings",
                            IsActive = true,
                            IsDeleted = false,
                            Order = 3,
                            Path = "/dashboard/settings",
                            Title = "Ayarlar"
                        },
                        new
                        {
                            Id = new Guid("7d9d5b63-64dc-4575-8110-9d4052e8cad0"),
                            CreatedAt = new DateTime(2025, 12, 12, 20, 55, 29, 526, DateTimeKind.Utc).AddTicks(2490),
                            Icon = "User",
                            IsActive = true,
                            IsDeleted = false,
                            Order = 1,
                            ParentId = new Guid("827d783b-15dc-40cc-bb5b-5f6c90368b43"),
                            Path = "/dashboard/users",
                            Title = "Kullanıcılar"
                        },
                        new
                        {
                            Id = new Guid("d4ed220e-1684-4029-b91e-cf67b032f0cd"),
                            CreatedAt = new DateTime(2025, 12, 12, 20, 55, 29, 526, DateTimeKind.Utc).AddTicks(2690),
                            Icon = "Users",
                            IsActive = true,
                            IsDeleted = false,
                            Order = 2,
                            ParentId = new Guid("827d783b-15dc-40cc-bb5b-5f6c90368b43"),
                            Path = "/dashboard/customers",
                            Title = "Müşteriler"
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("ScreenId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b07edd47-4fd6-4431-8d2c-0dd681f4df4c"),
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true,
                            IsDeleted = false,
                            RoleId = new Guid("d8663e5e-7494-4f81-8739-6e0de1c9858b"),
                            ScreenId = new Guid("86209540-e680-4672-866b-a0461eacfe25")
                        },
                        new
                        {
                            Id = new Guid("1f72af6c-0f97-4ba0-b27a-a895267277aa"),
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true,
                            IsDeleted = false,
                            RoleId = new Guid("c7b013f0-5201-4317-a5d4-9d0a5198f2f4"),
                            ScreenId = new Guid("86209540-e680-4672-866b-a0461eacfe25")
                        },
                        new
                        {
                            Id = new Guid("e50dd200-6f98-4651-9f06-c0b589ab4835"),
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = true,
                            CanUpdate = false,
                            IsDeleted = false,
                            RoleId = new Guid("72f8c5a2-9b1e-4239-847e-123456789abc"),
                            ScreenId = new Guid("86209540-e680-4672-866b-a0461eacfe25")
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8663e5e-7494-4f81-8739-6e0de1c9858b"),
                            IsDeleted = false,
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("c7b013f0-5201-4317-a5d4-9d0a5198f2f4"),
                            IsDeleted = false,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("72f8c5a2-9b1e-4239-847e-123456789abc"),
                            IsDeleted = false,
                            Name = "User"
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Screen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Screens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("86209540-e680-4672-866b-a0461eacfe25"),
                            Code = "PAGE_CUSTOMERS",
                            IsDeleted = false,
                            Name = "Customers"
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.VerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Token")
                        .IsUnique();

                    b.ToTable("VerificationTokens");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Customer", b =>
                {
                    b.HasOne("NextAdminAuth.Api.Models.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.MenuItem", b =>
                {
                    b.HasOne("NextAdminAuth.Api.Models.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Permission", b =>
                {
                    b.HasOne("NextAdminAuth.Api.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextAdminAuth.Api.Models.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.User", b =>
                {
                    b.HasOne("NextAdminAuth.Api.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextAdminAuth.Api.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Company", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.MenuItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
