// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextAdminAuth.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NextAdminAuth.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251212210123_RefactorBaseEntity")]
    partial class RefactorBaseEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NextAdminAuth.Api.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Tckn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Tckn")
                        .IsUnique();

                    b.ToTable("Customers", t =>
                        {
                            t.HasCheckConstraint("CK_Customer_Tckn_NoLeadingZero", "\"Tckn\" NOT LIKE '0%'");
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("110bed69-34fc-4354-8ecb-440cb77c35c1"),
                            CreatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 667, DateTimeKind.Utc).AddTicks(990),
                            Icon = "LayoutDashboard",
                            IsActive = true,
                            IsDeleted = false,
                            Order = 1,
                            Path = "/dashboard",
                            Title = "Ana Sayfa",
                            UpdatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 667, DateTimeKind.Utc).AddTicks(990)
                        },
                        new
                        {
                            Id = new Guid("550c6f29-6893-4134-942a-1f5ea44f4991"),
                            CreatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 667, DateTimeKind.Utc).AddTicks(2670),
                            Icon = "Users",
                            IsActive = true,
                            IsDeleted = false,
                            Order = 2,
                            Path = "#",
                            Title = "Yönetim",
                            UpdatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 667, DateTimeKind.Utc).AddTicks(2670)
                        },
                        new
                        {
                            Id = new Guid("0e3bbee9-1dc6-40ee-b16d-23bf119efbb4"),
                            CreatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 667, DateTimeKind.Utc).AddTicks(2670),
                            Icon = "Settings",
                            IsActive = true,
                            IsDeleted = false,
                            Order = 3,
                            Path = "/dashboard/settings",
                            Title = "Ayarlar",
                            UpdatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 667, DateTimeKind.Utc).AddTicks(2670)
                        },
                        new
                        {
                            Id = new Guid("7c5f2c1f-069b-46a5-b5f0-e4171a2104e4"),
                            CreatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 667, DateTimeKind.Utc).AddTicks(2670),
                            Icon = "User",
                            IsActive = true,
                            IsDeleted = false,
                            Order = 1,
                            ParentId = new Guid("550c6f29-6893-4134-942a-1f5ea44f4991"),
                            Path = "/dashboard/users",
                            Title = "Kullanıcılar",
                            UpdatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 667, DateTimeKind.Utc).AddTicks(2680)
                        },
                        new
                        {
                            Id = new Guid("320ac7fd-17f9-4ae3-833c-a389924320c0"),
                            CreatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 667, DateTimeKind.Utc).AddTicks(3000),
                            Icon = "Users",
                            IsActive = true,
                            IsDeleted = false,
                            Order = 2,
                            ParentId = new Guid("550c6f29-6893-4134-942a-1f5ea44f4991"),
                            Path = "/dashboard/customers",
                            Title = "Müşteriler",
                            UpdatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 667, DateTimeKind.Utc).AddTicks(3000)
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("ScreenId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("277deb13-6bf9-473b-ab50-3c644a66c18e"),
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true,
                            CreatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 668, DateTimeKind.Utc).AddTicks(1550),
                            IsDeleted = false,
                            RoleId = new Guid("d8663e5e-7494-4f81-8739-6e0de1c9858b"),
                            ScreenId = new Guid("4b545f7e-34fd-445e-b0aa-962843ce1540"),
                            UpdatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 668, DateTimeKind.Utc).AddTicks(1550)
                        },
                        new
                        {
                            Id = new Guid("37e079a4-ba94-472d-9516-7cf3b842f0ee"),
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true,
                            CreatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 668, DateTimeKind.Utc).AddTicks(3000),
                            IsDeleted = false,
                            RoleId = new Guid("c7b013f0-5201-4317-a5d4-9d0a5198f2f4"),
                            ScreenId = new Guid("4b545f7e-34fd-445e-b0aa-962843ce1540"),
                            UpdatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 668, DateTimeKind.Utc).AddTicks(3000)
                        },
                        new
                        {
                            Id = new Guid("2e797c0c-82ae-4d92-a756-0d3495826c94"),
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = true,
                            CanUpdate = false,
                            CreatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 668, DateTimeKind.Utc).AddTicks(3010),
                            IsDeleted = false,
                            RoleId = new Guid("72f8c5a2-9b1e-4239-847e-123456789abc"),
                            ScreenId = new Guid("4b545f7e-34fd-445e-b0aa-962843ce1540"),
                            UpdatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 668, DateTimeKind.Utc).AddTicks(3010)
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8663e5e-7494-4f81-8739-6e0de1c9858b"),
                            CreatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 667, DateTimeKind.Utc).AddTicks(9920),
                            IsDeleted = false,
                            Name = "SuperAdmin",
                            UpdatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 667, DateTimeKind.Utc).AddTicks(9920)
                        },
                        new
                        {
                            Id = new Guid("c7b013f0-5201-4317-a5d4-9d0a5198f2f4"),
                            CreatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 668, DateTimeKind.Utc).AddTicks(190),
                            IsDeleted = false,
                            Name = "Admin",
                            UpdatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 668, DateTimeKind.Utc).AddTicks(200)
                        },
                        new
                        {
                            Id = new Guid("72f8c5a2-9b1e-4239-847e-123456789abc"),
                            CreatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 668, DateTimeKind.Utc).AddTicks(200),
                            IsDeleted = false,
                            Name = "User",
                            UpdatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 668, DateTimeKind.Utc).AddTicks(200)
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Screen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Screens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b545f7e-34fd-445e-b0aa-962843ce1540"),
                            Code = "PAGE_CUSTOMERS",
                            CreatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 668, DateTimeKind.Utc).AddTicks(630),
                            IsDeleted = false,
                            Name = "Customers",
                            UpdatedAt = new DateTime(2025, 12, 12, 21, 1, 22, 668, DateTimeKind.Utc).AddTicks(630)
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.VerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Token")
                        .IsUnique();

                    b.ToTable("VerificationTokens");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Customer", b =>
                {
                    b.HasOne("NextAdminAuth.Api.Models.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.MenuItem", b =>
                {
                    b.HasOne("NextAdminAuth.Api.Models.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Permission", b =>
                {
                    b.HasOne("NextAdminAuth.Api.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextAdminAuth.Api.Models.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.User", b =>
                {
                    b.HasOne("NextAdminAuth.Api.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextAdminAuth.Api.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Company", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.MenuItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
