// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NextAdminAuth.Api.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NextAdminAuth.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251212204554_AddTcknToCustomer")]
    partial class AddTcknToCustomer
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NextAdminAuth.Api.Models.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Tckn")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Tckn")
                        .IsUnique();

                    b.ToTable("Customers", t =>
                        {
                            t.HasCheckConstraint("CK_Customer_Tckn_NoLeadingZero", "\"Tckn\" NOT LIKE '0%'");
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            Id = new Guid("840f6688-cdb4-4f8d-8628-c1eee72311fe"),
                            CreatedAt = new DateTime(2025, 12, 12, 20, 45, 53, 860, DateTimeKind.Utc).AddTicks(1030),
                            Icon = "LayoutDashboard",
                            IsActive = true,
                            Order = 1,
                            Path = "/dashboard",
                            Title = "Ana Sayfa"
                        },
                        new
                        {
                            Id = new Guid("7934b421-c4c6-422a-b3f4-13b214eff34d"),
                            CreatedAt = new DateTime(2025, 12, 12, 20, 45, 53, 860, DateTimeKind.Utc).AddTicks(2130),
                            Icon = "Users",
                            IsActive = true,
                            Order = 2,
                            Path = "#",
                            Title = "Yönetim"
                        },
                        new
                        {
                            Id = new Guid("004c9771-18fa-4c36-bc55-e1b941d5325f"),
                            CreatedAt = new DateTime(2025, 12, 12, 20, 45, 53, 860, DateTimeKind.Utc).AddTicks(2130),
                            Icon = "Settings",
                            IsActive = true,
                            Order = 3,
                            Path = "/dashboard/settings",
                            Title = "Ayarlar"
                        },
                        new
                        {
                            Id = new Guid("f0fb08cd-0dc3-42e0-b5a0-e84f31357028"),
                            CreatedAt = new DateTime(2025, 12, 12, 20, 45, 53, 860, DateTimeKind.Utc).AddTicks(2130),
                            Icon = "User",
                            IsActive = true,
                            Order = 1,
                            ParentId = new Guid("7934b421-c4c6-422a-b3f4-13b214eff34d"),
                            Path = "/dashboard/users",
                            Title = "Kullanıcılar"
                        },
                        new
                        {
                            Id = new Guid("a8170adc-ec96-45bf-9ebf-dfafe5de1a5c"),
                            CreatedAt = new DateTime(2025, 12, 12, 20, 45, 53, 860, DateTimeKind.Utc).AddTicks(2330),
                            Icon = "Users",
                            IsActive = true,
                            Order = 2,
                            ParentId = new Guid("7934b421-c4c6-422a-b3f4-13b214eff34d"),
                            Path = "/dashboard/customers",
                            Title = "Müşteriler"
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CanCreate")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanDelete")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanRead")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanUpdate")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ScreenId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("ScreenId");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("6c38eb97-7a71-4d44-b22a-abc0d7eda8cd"),
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true,
                            RoleId = new Guid("d8663e5e-7494-4f81-8739-6e0de1c9858b"),
                            ScreenId = new Guid("115a8021-9420-44c3-bb6b-4f55178f3f93")
                        },
                        new
                        {
                            Id = new Guid("840c5027-452e-44e6-924a-14db4befbcee"),
                            CanCreate = true,
                            CanDelete = true,
                            CanRead = true,
                            CanUpdate = true,
                            RoleId = new Guid("c7b013f0-5201-4317-a5d4-9d0a5198f2f4"),
                            ScreenId = new Guid("115a8021-9420-44c3-bb6b-4f55178f3f93")
                        },
                        new
                        {
                            Id = new Guid("bec2da88-5abf-4e3e-baba-a1e3c757566d"),
                            CanCreate = false,
                            CanDelete = false,
                            CanRead = true,
                            CanUpdate = false,
                            RoleId = new Guid("72f8c5a2-9b1e-4239-847e-123456789abc"),
                            ScreenId = new Guid("115a8021-9420-44c3-bb6b-4f55178f3f93")
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d8663e5e-7494-4f81-8739-6e0de1c9858b"),
                            Name = "SuperAdmin"
                        },
                        new
                        {
                            Id = new Guid("c7b013f0-5201-4317-a5d4-9d0a5198f2f4"),
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("72f8c5a2-9b1e-4239-847e-123456789abc"),
                            Name = "User"
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Screen", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Screens");

                    b.HasData(
                        new
                        {
                            Id = new Guid("115a8021-9420-44c3-bb6b-4f55178f3f93"),
                            Code = "PAGE_CUSTOMERS",
                            Name = "Customers"
                        });
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.VerificationToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email", "Token")
                        .IsUnique();

                    b.ToTable("VerificationTokens");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Customer", b =>
                {
                    b.HasOne("NextAdminAuth.Api.Models.Company", "Company")
                        .WithMany("Customers")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.MenuItem", b =>
                {
                    b.HasOne("NextAdminAuth.Api.Models.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Permission", b =>
                {
                    b.HasOne("NextAdminAuth.Api.Models.Role", "Role")
                        .WithMany("Permissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextAdminAuth.Api.Models.Screen", "Screen")
                        .WithMany()
                        .HasForeignKey("ScreenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("Screen");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.User", b =>
                {
                    b.HasOne("NextAdminAuth.Api.Models.Company", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NextAdminAuth.Api.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Company", b =>
                {
                    b.Navigation("Customers");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.MenuItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("NextAdminAuth.Api.Models.Role", b =>
                {
                    b.Navigation("Permissions");

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
